baseURL = "https://c1ay.github.io"
languageCode = "en-us"
title = "c1ay"
author = "c1ay"
theme = "paperback"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true


[params]
author = "c1ay"
intro = "c1ay home"
description = "web pythoner django, flask, celery"
authorimage = "header.png"
dateformat = "Jan 2, 2006"

# your name to display by the copyright sign
# default: undefined
AuthorName = "c1ay"

# tagline to show beneath homepage h1
# default: undefined
Tagline = "Hello, python!"

# number of posts to show on index
# default: 10
HomepagePosts = 3

# if set to true, social links will be displayed in the footer
# default: undefined
SocialLinks = true

# default: undefined
GithubUsername = "c1ay"

# default: undefined
TwitterUsername = "c1ay"

[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer,python,pythoner,pythonic"

[params.social]
github = "c1ay"
instagram = "<username>"
linkedin = "<username>"
twitter = "<username>"
facebook = "<username>"
google = "liukaiash"
stackoverflow = "<username>"
email = "c1ay@c1ay.cc"

[params.extra]
copyright = "© 2016. c1ay. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
hightlightjs = true


[[menu.main]]
    name = "post"
    weight = 100
    identifier = "post"
    url = "/post/"
[[menu.main]]
    name = "about"
    weight = 200
    identifier = "about"
    url = "/about/"
